spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mayikt_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mayikt:
  address: www.mayikt.com
  age:  ${random.int[20,40]} #22
  name: mayikt